- project:
    check:
      jobs:
        - opendev-buildset-registry
        - nebulous-monitoring-data-persistor-helm-lint
        - nebulous-monitoring-data-persistor-build-container-images
        - nebulous-monitoring-data-persistor-hadolint
        - nebulous-platform-apply-helm-charts
        - nox-linters
    gate:
      jobs:
        - opendev-buildset-registry
        - nebulous-monitoring-data-persistor-helm-lint
        - nebulous-monitoring-data-persistor-upload-container-images
        - nebulous-monitoring-data-persistor-hadolint
        - nebulous-platform-apply-helm-charts
        - nox-linters
    promote:
      jobs:
        - nebulous-monitoring-data-persistor-promote-container-images
